name: release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.repository == 'copperlight/huggsy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install Dependencies
        run: make install-deps
      - name: Make
        run: make
      - name: Create Deployment Bundle
        run: make zip
      - name: Update Function Code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: make update-function-code
